---
- name: F I R E W A L L Management
  hosts: 192.168.1.180
  tasks:
    - name: Open H T T P
      firewalld: 
        service: http
        state: disabled
        immediate: true
        permanent: true

...
