---
- name: lampstack
  hosts: 192.168.1.180
  become: yes
  vars:
          my_root_password: "pass1"
  tasks:

          - name: "Stop Services "
            systemd: name=httpd state=stopped enabled=no
          
          - name: "Updating F I R E W A L L "
            firewalld:
                   permanent: yes
                   zone: public
                   service: "{{ item }}"
                   state: disabled
            loop:
              - http
              - https
          
          - name: "Removing APACHE Server"
            dnf: name=httpd state=absent

                   
          - name: "R E S T A R T Firewall "
            systemd: 
              name: firewalld 
              state: restarted 
              enabled: yes

          - name: " Stopping M A R I A DB Service "
            service:
                    name: mariadb
                    state: stopped
                    enabled: false



          - name: " Removing M A R I A DB "
            yum:
                    name:
                            - mariadb-server
                            - python3-PyMySQL
                    state: absent

          
        
